routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// LOGIN AND REG
Route::get('/', function () {
    return view('auth.login');
});

// Login and Registration
Auth::routes();

// HOME
Route::get('/home', 'HomeController@index')->name('home');

// PDS RECORDS
Route::resource('pds-records', 'PdsRecordsController'); //FOR CRUD
Route::get('/pds-records', function () { //DISPLAY
     $pds = DB::table('pds_records')->get();
     // $pds = DB::table('pds_records')->paginate(12);
     return view('pds.index', ['pds' => $pds]);
});

// USER MANAGEMENT
Route::resource('manage-users', 'ManageUsersController'); //FOR CRUD
Route::get('/manage-users', function() {
	$user = DB::table('users')->get();
	return view('user.index', ['user' => $user]);
});

app/ManageUsers.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ManageUsers extends Model
{
	//
}

app/PdsRecords.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PdsRecords extends Model
{
    protected $guarded = [];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ManageUsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Response;
use App\ManageUsers;

class ManageUsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/PdsRecordsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Response;
use App\PdsRecords;

class PdsRecordsController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
         $this->middleware('auth');
    } 

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        $pds = DB::table('pds_records')->get();
        return view('/pds.index', ['pds' => $pds]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('/pds/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $keys = ['CSIDNO', 'SURNAME', 'FIRSTNAME', 'MIDDLENAME', 'NAMEEXT', 'DATEOFBIRTH', 'PLACEOFBIRTH', 'SEX', 'CIVILSTATUS', 'HEIGHT', 'WEIGHT', 'BLOODTYPE', 'GSIS', 'PAGIBIG', 'PHILHEALTH', 'SSS', 'TIN', 'AGENCYEMPNO', 'CITIZENSHIP', 'RESADDRESS', 'PERADDRESS', 'TELNO', 'MOBNO', 'EMAIL', 'SPOUSESURNAME', 'SPOUSEFIRSTNAME', 'SPOUSEMIDDLENAME', 'SPOUSENAMEEXT', 'SPOUSEOCC', 'SPOUSEBUSNAME', 'SPOUSEBUSADDRESS', 'SPOUSEBUSTEL',  'CHILDNAME',  'CHILDDOB',  'FATHERSURNAME',  'FATHERFIRSTNAME',  'FATHERMIDDLENAME',  'FATHERNAMEEXT',  'MOTHERMAIDENNAME',  'MOTHERSURNAME',  'MOTHERFIRSTNAME',  'MOTHERMIDDLENAME', 'ELEMSCHOOL',  'ELEMBASICEDUC',  'ELEMATTENDANCE',  'ELEMHIGHESTLEVEL',  'ELEMYEARGRADUATED',  'ELEMSCHOLARSHIP', 'HSSCHOOL',  'HSBASICEDUC',  'HSATTENDANCE',  'HSHIGHESTLEVEL',  'HSYEARGRADUATED',  'HSSCHOLARSHIP', 'VOCSCHOOL',  'VOCBASICEDUC',  'VOCATTENDANCE',  'VOCHIGHESTLEVEL',  'VOCYEARGRADUATED',  'VOCSCHOLARSHIP', 'COLSCHOOL',  'COLBASICEDUC',  'COLATTENDANCE',  'COLHIGHESTLEVEL',  'COLYEARGRADUATED',  'COLSCHOLARSHIP', 'GSSCHOOL',  'GSBASICEDUC',  'GSATTENDANCE',  'GSHIGHESTLEVEL',  'GSYEARGRADUATED',  'GSSCHOLARSHIP'];
        
        $input = $this->createQueryInput($keys, $request);
        PdsRecords::create($input);

        return redirect()->intended('/pds-records/create');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


    private function createQueryInput($keys, $request) {
        $queryInput = [];
        for($i = 0; $i < sizeof($keys); $i++) {
            $key = $keys[$i];
            $queryInput[$key] = $request[$key];
        }

        return $queryInput;
    }

}

resources/views/home.blade.php
@extends('layouts.app-template')

@section('content')
 
<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h3 class="text-themecolor">Dashboard</h3>
    </div>
    <div class="col-md-7 align-self-center">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
            <li class="breadcrumb-item active">Dashboard</li>
        </ol>
    </div>
    <div>
        <a href="{{url('pds-records/create')}}" title="Add Record" class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-plus text-white"></i></a>
    </div>
</div>

<div class="container-fluid">
    
    <div class="row">
        <!-- Column -->
        <div class="col-lg-3 col-md-6">
            <div class="card">
                <div class="card-body">
                    <!-- Row -->
                    <div class="row">
                        <div class="col-8"><h2>2376 <i class="ti-angle-down font-14 text-danger"></i></h2>
                            <h6><b style="color:#3dd42e; font-weight: 600; font-style: italic;">New Record</b><br>Added</h6></div>
                        <div class="col-4 align-self-center text-right  p-l-0">
                            <div id="sparklinedash3"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Column -->
        <div class="col-lg-3 col-md-6">
            <div class="card">
                <div class="card-body">
                    <!-- Row -->
                    <div class="row">
                        <div class="col-8"><h2 class="">3670 <i class="ti-angle-up font-14 text-success"></i></h2>
                            <h6>Casual<br>Appointment</h6></div>
                        <div class="col-4 align-self-center text-right p-l-0">
                            <div id="sparklinedash"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Column -->
        <div class="col-lg-3 col-md-6">
            <div class="card">
                <div class="card-body">
                    <!-- Row -->
                    <div class="row">
                        <div class="col-8"><h2>1562 <i class="ti-angle-up font-14 text-success"></i></h2>
                            <h6>Permanent<br>Appointment</h6></div>
                        <div class="col-4 align-self-center text-right p-l-0">
                            <div id="sparklinedash2"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Column -->
        <div class="col-lg-3 col-md-6">
            <div class="card">
                <div class="card-body">
                    <!-- Row -->
                    <div class="row">
                        <div class="col-8"><h2>35% <i class="ti-angle-down font-14 text-danger"></i></h2>
                            <h6>Records for<br>The year 2017</h6></div>
                        <div class="col-4 align-self-center text-right p-l-0">
                            <div id="sparklinedash4"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

   
</div>

@endsection

resources/views/layouts/app-template.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{{asset('/assets/images/favicon.ico')}}">
    <title>LGU | Urdaneta</title>
    <!-- Bootstrap Core CSS -->
    <link href="{{asset('/assets/plugins/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
    <!-- Morries chart CSS -->
    <link href="{{asset('/assets/plugins/morrisjs/morris.css')}}" rel="stylesheet">
    
    <link href="{{asset('/assets/plugins/wizard/steps.css')}}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{{asset('/css/style.css')}}" rel="stylesheet">
    <!-- You can change the theme colors from here -->
    <link href="{{asset('/css/colors/blue.css')}}" id="theme" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body class="fix-header fix-sidebar card-no-border">

    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" /> </svg>
    </div>

    <div id="main-wrapper">
        @include('layouts.header')

        @include('layouts.nav')

        <div class="page-wrapper">
            @yield('content')
            <footer class="footer">
                © 2018 LGU | Urdaneta
            </footer>
        </div>
       
    </div>

    <script src="{{asset('/assets/plugins/jquery/jquery.min.js')}}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{{asset('/assets/plugins/bootstrap/js/popper.min.js')}}"></script>

    <script src="{{asset('/assets/plugins/bootstrap/js/bootstrap.min.js')}}"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="{{asset('/js/jquery.slimscroll.js')}}"></script>
    <!--Wave Effects -->
    <script src="{{asset('/js/waves.js')}}"></script>
    <!--Menu sidebar -->
    <script src="{{asset('/js/sidebarmenu.js')}}"></script>
    <!--stickey kit -->
    <script src="{{asset('/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js')}}"></script>
    <script src="{{asset('/assets/plugins/sparkline/jquery.sparkline.min.js')}}"></script>
    <!--Custom JavaScript -->
    <script src="{{asset('/js/custom.min.js')}}"></script>
    <!-- <script src="{{asset('/js/jasny-bootstrap.js')}}"></script> -->
    <!-- ============================================================== -->
    <!-- This page plugins -->
    <!-- ============================================================== -->
    <!--morris JavaScript -->
    <script src="{{asset('/assets/plugins/raphael/raphael-min.js')}}"></script>
    <script src="{{asset('/assets/plugins/morrisjs/morris.min.js')}}"></script>
    <!-- sparkline chart -->
    <script src="{{asset('/assets/plugins/sparkline/jquery.sparkline.min.js')}}"></script>

    <script src="{{asset('/assets/plugins/datatables/jquery.dataTables.min.js')}}"></script>
    
    <script src="{{asset('/assets/plugins/wizard/jquery.steps.min.js')}}"></script>
    <script src="{{asset('/assets/plugins/wizard/jquery.validate.min.js')}}"></script>
    <!-- Sweet-Alert  -->
    <script src="{{asset('/assets/plugins/sweetalert/sweetalert.min.js')}}"></script>
    <script src="{{asset('/assets/plugins/wizard/steps.js')}}"></script>


    <script>
$(document).ready(function() {
    $('#myTable').DataTable();
    $(document).ready(function() {
        var table = $('#example').DataTable({
            "columnDefs": [{
                "visible": false,
                "targets": 2
            }],
            "order": [
                [2, 'asc']
            ],
            "displayLength": 25,
            "drawCallback": function(settings) {
                var api = this.api();
                var rows = api.rows({
                    page: 'current'
                }).nodes();
                var last = null;
                api.column(2, {
                    page: 'current'
                }).data().each(function(group, i) {
                    if (last !== group) {
                        $(rows).eq(i).before('<tr class="group"><td colspan="5">' + group + '</td></tr>');
                        last = group;
                    }
                });
            }
        });
    });
});
</script>
    <script src="{{asset('/assets/plugins/styleswitcher/jQuery.style.switcher.js')}}"></script>
</body>

</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{asset('/assets/images/favicon.ico')}}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    
    <!-- Fonts -->
    <!-- <link rel="dns-prefetch" href="https://fonts.gstatic.com"> -->
    <!-- <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css"> -->

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                            <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/nav.blade.php
<aside class="left-sidebar">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- User profile -->
        <div class="user-profile">
            <!-- User profile image -->
            <div class="profile-img"> <img src="{{asset('/assets/images/users/user-1.png')}}" alt="user" /> 
                     <!-- this is blinking heartbit-->
                    <div class="notify setpos"> <span class="heartbit"></span> <span class="point"></span> </div>
            </div>
            <!-- User profile text-->
            <div class="profile-text"> 
                    <h5>{{ Auth::user()->name }}</h5>
                    <a href="" class="" data-toggle="tooltip" title="Profile"><i class="mdi mdi-account-card-details"></i></a>
                    <a href="" class="" data-toggle="tooltip" title="Settings"><i class="mdi mdi-settings"></i></a>
                    <a href="{{ route('logout') }}" title="Logout" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="mdi mdi-power"></i></a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                    </form>
            </div>
        </div>
        <!-- End User profile text-->
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul>
                <li class="nav-devider"></li>

                <li> <a href="\home" aria-expanded="false"><i class="mdi mdi-chart-timeline"></i><span class="hide-menu">Dashboard</span></a>
                </li>

                <li> <a href="{{url('pds-records')}}" aria-expanded="false"><i class="mdi mdi-book-multiple"></i><span class="hide-menu">Personal Data Sheet</span></a>
                </li>

                <li> <a href="javascript:void(0);" aria-expanded="false"><i class="mdi mdi-file-export"></i><span class="hide-menu">Export Records</span></a>

                <li> <a href="javascript:void(0);" aria-expanded="false"><i class="mdi mdi-printer"></i><span class="hide-menu">Reports</span></a>
                </li>

                <li> <a href="{{url('manage-users')}}" aria-expanded="false"><i class="mdi mdi-account-key"></i><span class="hide-menu">Manage Users</span></a>
                </li>
            </ul>
        </nav>
    </div>
</aside>

resources/views/pds/base.blade.php
@extends('layouts.app-template')

@section('content')

<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h3 class="text-themecolor">Personal Data Sheet</h3>
    </div>
    <div class="col-md-7 align-self-center">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
            <li class="breadcrumb-item active">Personal Data Sheet</li>
        </ol>
    </div>
   <!--  <div>
        <a href="{{url('pds-records/create')}}" title="Add Record" class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-plus text-white"></i></a>
    </div> -->
</div>

@yield('action-content')

@endsection 

resources/views/pds/create.blade.php
@extends('pds.base')

@section('action-content')
<div class="container-fluid">
	<div class="row">
	    <div class="col-12">
	        <div class="card"> 
	            <div class="card-body wizard-content">
                    <div class="col-md-3 pull-right">
		                <a href="/pds-records" class="btn btn-block btn-lg btn-info col-lg-12 col-md-4 pull-right">Records</a>
		            </div>
		            <div class="col-md-9">
		                <h4 class="card-title">Add new record</h4>
		                <h6 class="card-subtitle">Description about adding data <a href="http://www.csc.gov.ph" target="_blank"><i>CSC</i></a></h6>
	                </div>
	                <form action="{{ route('pds-records.store') }}" method="POST" class="tab-wizard wizard-circle">
            		{{csrf_field()}}
	                    
	                    <!-- Step 1 -->
	                    <h6>Personal & Background<br>Information</h6>
	                  		@include('pds.page-1')
	                    <!-- Step 2 -->
	                    <h6>Eligibility &<br>Work Experience</h6>
	                  		@include('pds.page-2')
	                    	
	                    <!-- Step 3 -->
	                    <h6>Voluntary Work &<br>Learning Development</h6>
	                  		@include('pds.page-3')
	                    
	                    <!-- Step 4 -->
	                    <h6>References</h6>
	                  		@include('pds.page-4')
	                </form>
	            </div>
	        </div>
	    </div>
	</div>
</div>

@endsection

resources/views/pds/index.blade.php
@extends('pds.base')

@section('action-content')

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="col-md-3 pull-right">
                        <a href="{{ route('pds-records.create') }}" class="btn btn-lg waves-effect waves-light btn-block btn-info col-lg-12 col-md-4">Add Record</a>
                    </div>
                    <div class="col-md-9">
                    <h4 class="card-title">All Records</h4>
                    <h6 class="card-subtitle">Description <a href="http://www.csc.gov.ph" target="_blank"><i>CSC</i></a></h6>
                    </div>
                    <div class="table-responsive m-t-40">
                        <table id="myTable" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>PDS No</th>
                                    <th>LAST NAME</th>
                                    <th>FIRST NAME</th>
                                    <th>MIDDLE INITIAL</th>
                                    <th>EXT NAME</th>
                                    <th>ACTION</th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach($pds as $value)
                            <tr>
                                <td>{{$value -> CSIDNO}}</td>
                                <td>{{$value -> SURNAME}}</td>
                                <td>{{$value -> FIRSTNAME}}</td>
                                <td>{{$value -> MIDDLENAME}}</td>
                                <td>{{$value -> NAMEEXT}}</td>
                                <td>
                                    <a href="" class="btn btn-xs btn-info">Update</a>
                                    <a href="" class="btn btn-xs btn-primary">View</a>
                                    <a href="" class="btn btn-xs btn-danger"><i class="fa fa-trash"></i></a>
                                </td>
                            </tr>
                            @endforeach                           
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> 

@endsection

resources/views/pds/page-2.blade.php
<section>

<!-- IV. ELIGIBILITY -->
<h2 class="box-title text-info"><b>IV. Eligibility</b></h2>

<hr class="m-t-12 m-b-10">

<h2 class="box-title text-info"><b>IV. Work Experience</b></h2>


</section>

resources/views/user/create.blade.php
@extends('user.base')

@section('action-content')


@endsection

resources/views/user/index.blade.php
@extends('user.base')

@section('action-content')
<div class="container-fluid">
	<div class="row">
	    <div class="col-12">
	        <div class="card">
	            <!-- .left-right-aside-column-->
	            <div class="contact-page-aside">
	                <!-- .left-aside-column-->
	                <div class="left-aside bg-light-part">
	                    <ul class="list-style-none">
	                        <li class="box-label"><a href="javascript:void(0)">All Users <span>1</span></a></li>
	                        <li class="divider"></li>
	                        <li><a href="javascript:void(0)">Administrator <span>0</span></a></li>
	                        <li><a href="javascript:void(0)">User <span>0</span></a></li>
	                        <li><a href="javascript:void(0)">Guest <span>0</span></a></li>
	                    </ul>
	                </div>
	                <!-- /.left-aside-column-->
	                <div class="right-aside ">
                    <div class="col-12">
                    <div class="col-md-3 pull-right">
                        <a href="{{ route('manage-users.create') }}" class="btn btn-lg waves-effect waves-light btn-block btn-info col-lg-12 col-md-4">Add User</a>
                    </div>
                    <div class="col-md-9">
                    <h4 class="card-title">List of Administrator and Users</h4>
                    <h6 class="card-subtitle">Description <a href="http://www.csc.gov.ph" target="_blank"><i>CSC</i></a></h6>
                    </div>
                    <div class="table-responsive m-t-40">
                        <table id="myTable" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Role</th>
                                    <th>Email</th>
                                    <th>Date Registered</th>
                                    <th>Action</th>
                                </tr>
                            </thead> 
                            <tbody>
                            @foreach($user as $users)
                            <tr>
                                <td>{{ $users->name }}</td>
                                <td>Administrator</td>
                                <td>{{ $users->email }}</td>
                                <td>{{ date('F d, Y', strtotime($users->created_at)) }}</td>
                                <td>
                                    <a href="" class="btn btn-xs btn-info">Update</a>
                                    <a href="" class="btn btn-xs btn-danger"><i class="fa fa-trash"></i></a>
                                </td>
                            </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    </div>
	                </div>
	                <!-- /.left-right-aside-column-->
	            </div>
	        </div>
	    </div>
	</div>
</div>
@endsection